### ISSUE TITLE
Refactoring for swift3.0, clean code for massive view controller

### ISSUE THREAD

**Issue by suzuki-0000** [suzuki-0000/SKPhotoBrowser#125]
now I'm implementing. and some issue will be fixed with this.
this spec will be v3.0.0. and some breaking changes will happen.

- add
- [x] add ChangeLog file #123 
- [x] How to using custom cache instead of default cache #124 

- update
- [ ] refactor code. some breaking changes(because it is hard to implement to new function now.)

- bugfix
- [x] Parent View disappears when dismissed. #120
- [x] Glitch when origin imageview is not correct size #108 
- [x] Problems with the "long" photo #116

**Comment by MarvinNazari** [comment]
hi @suzuki-0000, any ETA on this?

**Comment by suzuki-0000** [comment]
hi @MarvinNazari, I will update merge this issue until this month.
you can check pull request which is working now. https://github.com/suzuki-0000/SKPhotoBrowser/pull/127
welcome to any suggestions.
